/**
 * CoachView — Dedicated coach message feed
 *
 * Shows all AI coach messages chronologically, grouped by date.
 * Messages are generated by useCoachMessages() and stored in localStorage.
 * Marks all as read when the view is opened.
 */

import { useEffect, useState } from 'react';
import { useCoachMessages, type CoachMessage } from '../hooks/useCoachMessages';

const TYPE_LABELS: Record<CoachMessage['type'], { label: string; color: string }> = {
  daily_brief:         { label: 'Daily Brief',          color: 'var(--c-accent-purple)' },
  task_complete:       { label: 'Task Complete',         color: 'var(--c-accent-green)'  },
  streak_milestone:    { label: 'Streak',                color: 'var(--c-accent-amber)'  },
  plan_adjustment:     { label: 'Plan Adjusted',         color: 'var(--c-accent-purple)' },
  pattern_observation: { label: 'Pattern Observation',   color: 'var(--c-text-tertiary)' },
  intro:               { label: 'Welcome',               color: 'var(--c-accent-purple)' },
};

function groupByDate(messages: CoachMessage[]): Array<{ label: string; messages: CoachMessage[] }> {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const yesterday = new Date(today);
  yesterday.setDate(yesterday.getDate() - 1);

  const groups = new Map<string, CoachMessage[]>();

  for (const msg of [...messages].reverse()) {
    const d = new Date(msg.timestamp);
    d.setHours(0, 0, 0, 0);

    let label: string;
    if (d.getTime() === today.getTime()) {
      label = 'Today';
    } else if (d.getTime() === yesterday.getTime()) {
      label = 'Yesterday';
    } else {
      label = d.toLocaleDateString('en-US', { month: 'long', day: 'numeric' });
    }

    if (!groups.has(label)) groups.set(label, []);
    groups.get(label)!.push(msg);
  }

  return Array.from(groups.entries()).map(([label, messages]) => ({ label, messages }));
}

function formatTime(iso: string): string {
  return new Date(iso).toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' });
}

function MessageCard({ msg }: { msg: CoachMessage }) {
  const typeInfo = TYPE_LABELS[msg.type] ?? { label: msg.type, color: 'var(--c-text-tertiary)' };

  return (
    <div style={{
      padding: '14px 16px',
      backgroundColor: 'var(--c-bg-primary)',
      border: '1px solid var(--c-border-subtle)',
      borderRadius: 12,
      boxShadow: 'var(--c-shadow-card)',
      borderLeft: msg.read ? '1px solid var(--c-border-subtle)' : '3px solid var(--c-accent-purple)',
    }}>
      {/* Type chip */}
      <div style={{
        display: 'inline-flex',
        alignItems: 'center',
        gap: 5,
        marginBottom: 8,
      }}>
        <span style={{
          width: 6,
          height: 6,
          borderRadius: '50%',
          backgroundColor: typeInfo.color,
          flexShrink: 0,
        }} />
        <span style={{
          fontSize: 11,
          fontWeight: 600,
          color: typeInfo.color,
          letterSpacing: '0.04em',
          textTransform: 'uppercase',
          fontFamily: 'var(--c-font-body)',
        }}>
          {typeInfo.label}
        </span>
      </div>

      {/* Message text */}
      <p style={{
        fontFamily: 'var(--c-font-body)',
        fontSize: 14,
        color: 'var(--c-text-primary)',
        lineHeight: 1.6,
        margin: '0 0 8px',
      }}>
        {msg.text}
      </p>

      {/* Timestamp */}
      <p style={{
        fontSize: 11,
        color: 'var(--c-text-quaternary)',
        margin: 0,
        fontFamily: 'var(--c-font-body)',
      }}>
        {formatTime(msg.timestamp)}
      </p>
    </div>
  );
}

export default function CoachView() {
  const { getMessages, markAllRead } = useCoachMessages();
  const [messages] = useState<CoachMessage[]>(() => getMessages());

  useEffect(() => {
    // Mark all read when the view opens
    markAllRead();
  }, [markAllRead]);

  const groups = groupByDate(messages);

  return (
    <div style={{ fontFamily: 'var(--c-font-body)' }}>
      {/* Page header */}
      <div style={{ marginBottom: 28 }}>
        <h1 style={{
          fontFamily: 'var(--c-font-display)',
          fontSize: 28,
          fontWeight: 500,
          color: 'var(--c-text-primary)',
          letterSpacing: '-0.02em',
          margin: '0 0 4px',
        }}>
          Your Coach
        </h1>
        <p style={{
          fontSize: 13,
          color: 'var(--c-text-tertiary)',
          margin: 0,
        }}>
          Notes, insights, and plan adjustments from Coheren as you progress.
        </p>
      </div>

      {/* Message feed */}
      {groups.length === 0 ? (
        <div style={{
          padding: '48px 0',
          textAlign: 'center',
        }}>
          <p style={{
            fontSize: 15,
            color: 'var(--c-text-tertiary)',
            margin: 0,
          }}>
            Your coach messages will appear here as you progress.
          </p>
          <p style={{
            fontSize: 13,
            color: 'var(--c-text-quaternary)',
            margin: '8px 0 0',
          }}>
            Complete your first task to get started.
          </p>
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
          {groups.map(({ label, messages: groupMsgs }) => (
            <div key={label}>
              {/* Date label */}
              <div style={{
                fontSize: 11,
                fontWeight: 600,
                color: 'var(--c-text-quaternary)',
                letterSpacing: '0.06em',
                textTransform: 'uppercase',
                marginBottom: 10,
                fontFamily: 'var(--c-font-body)',
              }}>
                {label}
              </div>

              {/* Messages in this group */}
              <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                {groupMsgs.map(msg => (
                  <MessageCard key={msg.id} msg={msg} />
                ))}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
